package mx.com.endtoend.domain.commons.constants;

public enum ActionOrder {

	CREATE_ORDER,
	UPDATE_ORDER,
	CANCEL_ORDER,
	CONVERT_ORDER,
	APPROVE_ORDER,
	AUTOMATIC_CANCEL_ORDER,
	UPDATE_PYMENT,
	GENERATE_CREDIT_NOTE,
	APPROVE_CREDIT_NOTE,
	APPROVE_CREDIT_NOTE_PAYMENT
	;
}
