package mx.com.endtoend.domain.commons.constants;

public enum GenericIdentifyMethods {

/*
 * CONSTANTES PARA LA IDENTIFICACION DE LOS METODOS DESARROLLADOS POR CADA MODULO DEL SISTEMA
 */
	
	//CLIENTS
	CLI_CONF_ONE,
	CLI_CONF_TWO,
	//CATALOGUE
	CAT_CONF_ONE,
	CAT_CONF_TWO,
	//CATALOGUES
	CAT_CLIENT_ONE,
	CAT_ARTICLE_ONE,
	CAT_ADDRESS_ONE,
	CAT_BRANCH_ONE,
	//USER_CONFIGURATIONS
	USR_CONF_ONE,
	//ARTICLES
	ART_SERCH_ONE,
	ART_SERCH_TWO,
	//ORDERS_BUSINESS
	ORDER_BUSINESS_ONE,
	ORDER_BUSINESS_TWO,
	//ORDERS
	QUOTE_ONE,
	QUOTE_TWO,
	SALE_AD_ONE,
	SALE_AD_TWO,
	SALE_CASH_ONE,
	SALE_CASH_TWO,
	SALE_DIRECT_ONE,
	SALE_DIRECT_TWO,
	SALE_CASH_COUNTER_ONE,
	SALE_CASH_COUNTER_TWO,
	SALE_HOME_DELIVERY_ONE,
	SALE_HOME_DELIVERY_TWO,
	SALE_COUNTER_ONE,
	SALE_COUNTER_TWO,
	SALE_PICKUP_WAREHOUSE_ONE,
	SALE_PICKUP_WAREHOUSE_TWO,
	SALE_PICKUP_CUSTOMER_ONE,
	SALE_PICKUP_CUSTOMER_TWO,
	//ORDER_CONFIGURATION
	ORDER_CONFIGURATION_ONE,
	//ORDER-MONITORING
	ORDER_MONITORING_ONE,
	//CASH
	OPENING_INSTRUMENT_ONE,
	CLOSING_INSTRUMENT_ONE,
	CREDIT_CARD_REFERENCE_ONE,
	EMAIL_CASH_CONFIGURATION_ONE,
	BANK_REFERENCE_ONE,
	//OPENININGS
	OPENING_OPERATION_ONE,
	//CLOSINGS
	CLOSING_OPERATION_ONE,
	//CUSTOM ARTICLES
	CUS_ART_ONE,
	//PAYMENTS
	PAYMENT_ONE,
	PAYMENT_CREDIT_ONE,
	//REPORTS BY CASH
	REPORT_CASH_ONE,
	//REPORTS BY SALES
	REPORT_SALE_ONE,
	REPORT_SALE_BRANCH_EMPLOYEE_ONE,
	REPORT_SALE_ARTICLE_ONE,
	REPORT_CLOSING_ONE,
	//CREDIT NOTES
	CREDIT_NOTE_ONE,
	//ADVERTISING
	ADVERTISING_ONE,
	//RECHARGE
	RECHARGE_ONE
	
	;
}
