######									######
###### CONFIGURACIONES GOBALES			######
######									###### 

#spring.cloud.service-registry.auto-registration.enabled=false
#eureka.client.enabled=false
#eureka.client.serviceUrl.registerWithEureka=fal
##EUREKA CONFIGURATION
spring.application.name=sm-core-web
eureka.instance.instance-id=${spring.cloud.client.hostname}:${server.port}:${spring.application.name}:${random.value}
eureka.instance.hostname=localhost
eureka.client.service-url.defaultZone=http://10.253.4.81:8761/eureka

##DOCKER - PRINCIPAL DATABASE
app.datasource.url=jdbc:mysql://10.253.3.56/pos_security_pd
app.datasource.username=calzada_pd_test
app.datasource.password=gUrECu64XGRePTDht3qVHx
app.datasource.driver-class-name=com.mysql.cj.jdbc.NonRegisteringDriver

## CONFIGURACION DE PUERTO, AMBIENTE Y VERSION
server.port=8111
app.version= 2.0.0
environment.active = PPR

## CONEXION A RABBIT MQ
spring.rabbitmq.host=10.253.4.81
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

##CONFIGURACION DE LOG
logging.file.name=sm-core-1.log
logging.file.max-size=300MB
logging.file.max-history=5
logging.file.clean-history-on-start=true

######									######
###### COMPANIA CALZADA Y SUB COMPANIAS ######
######									######

#DATABASE ORACLE CALZADA
app.calzadaOracle.datasource.driver-class-name=oracle.jdbc.OracleDriver
app.calzadaOracle.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
app.calzadaOracle.datasource.url=jdbc:oracle:thin:@//10.194.40.161:1521/FCALPD
app.calzadaOracle.datasource.username=PRODDTA
app.calzadaOracle.datasource.password=PRODDTA

##DOCKER - DATABASE MySQL CALZADA
app.datasource.calzada.url=jdbc:mysql://10.253.3.56/calzada_pos_pd
app.datasource.calzada.username=calzada_pd_test
app.datasource.calzada.password=gUrECu64XGRePTDht3qVHx
app.datasource.calzada.driver-class-name=com.mysql.cj.jdbc.NonRegisteringDriver

#DATABASE SQLServer CALZADA
app.calzadaSQL.datasource.url=jdbc:sqlserver://10.253.3.22:1433;database=CalzadaProd
app.calzadaSQL.datasource.username=POSCALPD
app.calzadaSQL.datasource.password=C41zP0$2023
app.calzadaSQL.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

##DOCKER - DATABASE MySQL CALZADA - FRAGUA-00009
app.datasource.fragua.url=jdbc:mysql://10.253.3.56/fragua_pos_pd
app.datasource.fragua.username=calzada_pd_test
app.datasource.fragua.password=gUrECu64XGRePTDht3qVHx
app.datasource.fragua.driver-class-name=com.mysql.cj.jdbc.Driver

#DATABASE SQLServer FRAGUA - 00009
app.fraguaSQL.datasource.url=jdbc:jtds:sqlserver://10.253.3.22:54398;database=FRAGUA_POS_Prod;instance=BDFRAGUA
app.fraguaSQL.datasource.username=POS
app.fraguaSQL.datasource.password=-uyJs3-m_QnSkYRerS^3F49r
app.fraguaSQL.datasource.driver-class-name=net.sourceforge.jtds.jdbc.Driver

#URL PARA LA OBTENCION DE NEXT_NUMBER DE LAS ORDENES DEL SISTEMA / JDE
app.calzada.jde.consecutive.generator.url=http://10.253.4.81:8201/order/next-order-number/
app.calzada.jde.company.code=00001

#URL PARA LA OBTENCION DE BATCH-FOLIO DE LAS ORDENES DEL SISTEMA / JDE
app.calzada.jde.batchFolio.generator.url=http://10.253.4.81:8201/order/next-batch-folio/

#URL PARA RECARGAS DE TIEMPO AIRE
app.calzada.selia.generator.url=http://200.94.104.94:32005/

#RABBIT MQ
##COLA DE ATENCION POS LEGACY CALZADA
app.calzada.queue.oreder.name=saveOrderCalzada
app.calzada.queue.oreder.direct.name=saveOrderDirectCalzada
app.calzada.queue.approve.oreder.name=approveOrderCalzada
app.calzada.queue.cancel.oreder.name=cancelOrderCalzada
app.calzada.queue.status.oreder.name=changeStatusOrderCalzada

##COLA DE ATENCION POS LEGACY FRAGUA
app.fragua.queue.order.name=saveOrderFragua
app.fragua.queue.oreder.direct.name=saveOrderDirectFragua
app.fragua.queue.approve.oreder.name=approveOrderFragua
app.fragua.queue.cancel.oreder.name=cancelOrderFragua
app.fragua.queue.status.oreder.name=changeStatusOrderFragua

##COLA DE ATENCION CALZADA JDE
app.calzada.queue.jde.order.name=saveOrderCalzadaJDE
app.calzada.queue.jde.credit.note.name=saveCreditNoteCalzadaJDE
app.calzada.queue.jde.invoice.name=saveInvoiceRecorCalzadadJDE

##COLA DE ATENCION FRAGUA JDE
app.fragua.queue.jde.order.name=saveOrderFraguaJDE
app.fragua.queue.jde.credit.note.name=saveCreditNoteFraguaJDE
app.fragua.queue.jde.invoice.name=saveInvoiceRecorFraguaJDE

######										######
###### COMPANIA CARREDANA Y SUB COMPANIAS   ######
######									    ######

#DATABASE ORACLE
app.carredana.oracle.datasource.driver-class-name=oracle.jdbc.OracleDriver
app.carredana.oracle.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
app.carredana.oracle.datasource.url=jdbc:oracle:thin:@ete-rac10.etecloud.mx:1521/FCARPD
app.carredana.oracle.datasource.username=CARRDTA
app.carredana.oracle.datasource.password=CARRDTA

##DOCKER - DATABASE MySQL
app.carredana.mysql.datasource.url=jdbc:mysql://10.253.3.56/carredana_pos_pd
app.carredana.mysql.datasource.driver-class-name=com.mysql.cj.jdbc.NonRegisteringDriver
app.carredana.mysql.username=calzada_pd_test
app.carredana.mysql.password=gUrECu64XGRePTDht3qVHx

##DATABASE MySQL CARREDANA - ZAPATA
app.zapata.mysql.datasource.url=jdbc:mysql://10.253.3.56/zapata_pos_pd
app.zapata.mysql.driver-class-name=com.mysql.cj.jdbc.Driver
app.zapata.mysql.username=calzada_pd_test
app.zapata.mysql.password=gUrECu64XGRePTDht3qVHx

##DATABASE MySQL CARREDANA - FERRESAMANO
app.fsamano.mysql.datasource.url=jdbc:mysql://10.253.3.56/ferresamano_pos_pd
app.fsamano.mysql.driver-class-name=com.mysql.cj.jdbc.Driver
app.fsamano.mysql.username=calzada_pd_test
app.fsamano.mysql.password=gUrECu64XGRePTDht3qVHx

##DATABASE ORACLE FERRESAMANO
app.ferresamano.oracle.datasource.driver-class-name=oracle.jdbc.OracleDriver
app.ferresamano.oracle.jpa.database-platform=org.hibernate.dialect.Oracle12cDialect
app.ferresamano.oracle.datasource.url=jdbc:oracle:thin:@10.252.3.9:1521/RSAMPD
app.ferresamano.oracle.datasource.username=CRPDTA
app.ferresamano.oracle.datasource.password=CRPDTA

#URL PARA LA OBTENCION DE NEXT_NUMBER DE LAS ORDENES DEL SISTEMA / JDE
app.carredana.jde.consecutive.generator.url=http://10.253.4.81:8210/order/next-order-number/
app.carredana.jde.company.code=00002

#URL PARA LA OBTENCION DE BATCH-FOLIO DE LAS ORDENES DEL SISTEMA / JDE
app.carredana.jde.batchFolio.generator.url=http://10.253.4.81:8210/order/next-batch-folio/

#RABBIT MQ

##COLA DE ATENCION CARREDANA JDE
app.carredana.queue.jde.order.name=saveOrderCarredanaJDE
app.carredana.queue.jde.credit.note.name=saveCreditNoteCarredanaJDE
app.carredana.queue.jde.invoice.name=saveInvoiceRecorCarredanaJDE

##COLA DE ATENCION CARREDANA - ZAPATA JDE
app.zapata.queue.jde.order.name=saveOrderZapataJDE
app.zapata.queue.jde.credit.note.name=saveCreditNoteZapataJDE
app.zapata.queue.jde.invoice.name=saveInvoiceRecorZapataJDE

##COLA DE ATENCION CARREDANA - FERRESAMANO JDE
app.fsamano.queue.jde.order.name=saveOrderFSamanoJDE
app.fsamano.queue.jde.credit.note.name=saveCreditNoteFSamanoJDE
app.fsamano.queue.jde.invoice.name=saveInvoiceRecorFSamanoJDE

app.demo.jde.company.code=DEMO