SOURCE: chapter7/microservices/movies-store/Dockerfile.test
MIME: text/plain; charset=us-ascii
----- BEGIN CONTENT -----
FROM node:14.17.0

WORKDIR /app

COPY package-lock.json package.json .

RUN npm i

COPY . .
----- END CONTENT -----
