SOURCE: chapter12/functions/movies-marketplace/Dockerfile.test
MIME: text/plain; charset=us-ascii
----- BEGIN CONTENT -----
FROM node:14.0.0

ENV CHROME_BIN=chromium

WORKDIR /app

RUN apt-get update && apt-get install -y chromium

COPY package-lock.json .
COPY package.json .

RUN npm i && npm i -g @angular/cli

COPY . .
----- END CONTENT -----
