apiVersion: v1
kind: Service
metadata:
  name: pos-online
  namespace: pos-online
  labels:
    app: pos-online
spec:
  type: ClusterIP
  ports:
    - port: 8111
      targetPort: 8111
      protocol: TCP
      name: http
  selector:
    app: pos-online
