SOURCE: chapter12/functions/movies-loader/Dockerfile.test
MIME: text/plain; charset=us-ascii
----- BEGIN CONTENT -----
FROM python:3.7.3

WORKDIR /app 

COPY requirements.txt .
RUN pip install -r requirements.txt

COPY test_index.py .
COPY movies.json .
----- END CONTENT -----
