SOURCE: chapter11/jx/movies-store/Dockerfile
MIME: text/plain; charset=us-ascii
----- BEGIN CONTENT -----
FROM alpine
EXPOSE 8080
ENTRYPOINT ["/jx-movies-store"]
COPY ./bin/ /
----- END CONTENT -----
