	package mx.com.endtoend.infrastructure.commons.constants;

public enum PermissionEnum {


	//PERMISOS DE ETE ADMIN PARA CREACION DE USUARIOS ADMINISTRADORES
	ETE_CREATE_USER,
	ETE_UPDATE_USER_BYID,
	ETE_ENABLED_USER_BYID,
	ETE_VIEW_USER_BYID,
	ETE_VIEW_ACTIVE_USERS,
	ETE_VIEW_IANCTIVE_USERS,
	//PERMISOS DE ETE ADMIN PARA CREACION DE COMPANIAS 
	ETE_CREATE_COMPANY,
	ETE_UPDATE_COMPANY_BYID,
	ETE_VIEW_COMPANY_BYID,
	ETE_VIEW_ALL_COMPANIES,
	ETE_VIEW_METHODS_BY_MODULE,
	//PERMISOS PARA SUCURSALES
	BRANCHES_CREATE,
	BRANCHES_UPDATE,
	BRANCHES_VIEW_ALL,
	BRANCHES_VIEW_BYID,
	UPDATE_EXTERNAL_SERVICE,
	//PERMISOS PARA EL CODIGO DE ESTRATTEGIA
	ETE_STARTEGY_LIST,
	//PERMISOS PARA MODULO DE USUARIOS
	USERS_CREATE,
	USERS_UPDATE_BYID,
	USERS_ENABLED_BYID,
	USERS_VIEW_BYID,
	USERS_VIEW_ACTIVE_LIST,
	USERS_VIEW_INACTIVE_LIST,
	USERS_CHANGE_STATUS,
	USERS_CHANGE_STATUS_OPERATIONAL,
	//PERMISOS PARA MODULO DE ROLES
	ROLES_CREATE,
	ROLES_UPDATE_BYID,
	ROLES_ENABLED_BYID,
	ROLES_VIEW_BYID,
	ROLES_VIEW_ACTIVE_LIST,
	ROLES_VIEW_INACTIVE_LIST,
	//PERMISOS PARA MODULO DE PERMISOS
	PERMISSIONS_VIEW_CLIENT_LIST,
	PERMISSIONS_VIEW_ADMIN_LIST,
	//PERMISOS PARA PANELES 
	VIEW_ADMIN_PANLE,
	VIEW_COMPANY_PANEL,
	VIEW_COMPANY_PANEL_MANAGEMENT,
	//PERMISOS PARA CLIENT
	CLIENT_CREATE,
	CLIENT_UPDATE,
	CLIENT_LIST_ID,
	CLIENT_LIST,
//	CLIENT_DIRECTION_LIST_UVICATION,
//	CLIENT_DIRECTION,
	CLIENT_UPDATE_SHIPPINGADDRESS,
	CLIENT_CREATE_SHIPPINGADDRESS,
	CLIENT_SHIPPINGADDRESS_LIST,
	CLIENT_SHIPPINGADDRESS,
	//PERMISOS PARA CLIENT CATALOG
	CATALOGUE,
	//PERMISOS PARA ALMACENES
	WAREHOUSE_LIST,
	//PERMISOS PARA LA GESTION DE EMPLEADOS
	USERS_CONFIG_CREATE,
	USERS_CONFIG_UPDATE_BYID,
	USERS_CONFIG_VIEW_BYID,
	USERS_CONFIG_VIEW_GENERIC_LISTS,
	USERS_CONFIG_VIEW_GENERIC_LISTS_OPERATIONAL,
	//PERMISOS PARA ARTICULOS
	ARTICLES_FIND_BY_PARAMS,
	//PERMISOS PARA ORDENES
	ORDERS_CREATE,
	ORDERS_UPDATE,
	ORDERS_MANUAL_CANCEL,
	ORDERS_APPROVE,
	ORDERS_CONVERT,
	ORDERS_SERCH,
	ORDERS_VIEW_DETAIL,
	ORDERS_VIEW_HISTORICAL,
	//PERMISOS PARA CONFIGURACION DE ORDENES
	ORDERS_CONFIG_CREATE,
	ORDERS_CONFIG_UPDATE,
	ORDERS_CONFIG_VIEW_DETAIL,
	ORDERS_CONFIG_VIEW_LIST,
	//PERMISOS PARA LA GESTION DE ARTICULOS PERSONALIZADOS
	CUST_ARTICLES_CREATE,
	CUST_ARTICLES_UPDATE,
	CUST_ARTICLES_ENABLED_BYID,
	CUST_ARTICLES_VIEW_ACTIVE_LIST,
	CUST_ARTICLES_VIEW_INACTIVE_LIST,
	CUST_ARTICLES_VIEW_BYID,
	CUST_ARTICLES_VIEW_ACTIVE_LIST_OPERATIONAL,
	//PERMISOS PARA LA ADMINISTRACION DE INSTRUMENTOS DE PAGO-APERTURAS
	OPEN_PAYMENT_INSTRUMENT_CREATE,
	OPEN_PAYMENT_INSTRUMENT_UPDATE,
	OPEN_PAYMENT_INSTRUMENT_VIEW_BYID,
	OPEN_PAYMENT_INSTRUMENT_VIEW_ACTIVE_LIST,
	OPEN_PAYMENT_INSTRUMENT_VIEW_INACTIVE_LIST,
	OPEN_PAYMENT_INSTRUMENT_VIEW_ACTIVE_LIST_OPERATIONAL,
	//PERMISOS PARA LA ADMINISTRACION DE INSTRUMENTOS DE PAGO-CIERRES
	CLOSE_PAYMENT_INSTRUMENT_CREATE,
	CLOSE_PAYMENT_INSTRUMENT_UPDATE,
	CLOSE_PAYMENT_INSTRUMENT_VIEW_BYID,
	CLOSE_PAYMENT_INSTRUMENT_VIEW_ACTIVE_LIST,
	CLOSE_PAYMENT_INSTRUMENT_VIEW_INACTIVE_LIST,
	CLOSE_PAYMENT_INSTRUMENT_VIEW_ACTIVE_LIST_OPERATIONAL,
	//PERMISOS PARA LA ADMINISTRACION DE COBROS
	PAYMENT_SEARCH_ORDER,
	PAYMENT_CREATE_ORDER,
	PAYMENT_MANUAL_CANCEL,
	PAYMENT_REPRINT_TICKET,
	PAYMENT_SEARCH,
	//PERMISOS PARA LA ADMINISTRACION DE COBROS CON CREDITO
	PAYEMNT_CREDIT_CREATE,
	//OPENINGS
	OPENING_OPERATION_CREATE,
	//CLOSINGS
	CLOSING_OPERATION_CREATE,
	//PERMISOS PARA LA ADMINISTRACION DE REFERENCIAS DE TARJETAS DE CREDITO
	CREDIT_CARD_CREATE,
	CREDIT_CARD_UPDATE,
	CREDIT_CARD_VIEW_BYID,
	CREDIT_CARD_VIEW_ACTIVE_LIST,
	CREDIT_CARD_VIEW_INACTIVE_LIST,
	CREDIT_CARD_VIEW_ACTIVE_LIST_OPERATIONAL,
	//PERMISOS PARA REPORTES
	GENERATE_CASH_REPORT,
	//PERMISOS PARA CONFIGURACION DE ENVIO DE REPORTES DE CAJA
	EMAIL_CASH_CREATE,
	EMAIL_CASH_UPDATE,
	EMAIL_CASH_VIEW,
	//PERMISOS PARA LA CONFIGURACION DE REFERENCIAS BANCARIAS
	BANK_CREATE,
	BANK_UPDATE,
	BANK_VIEW_BYID,
	BANK_VIEW_ACTIVE_LIST,
	BANK_VIEW_INACTIVE_LIST,
	BANK_VIEW_ACTIVE_LIST_OPERATIONAL,
	//PERMISOS PARA LA GESTION DE NOTAS DE CREDITO
	CREDIT_NOTE_CREATE,
	CREDIT_NOTE_SEARCH,
	//PERMISOS PARA LA GESTION  DE REPORTES DE VENTAS
	GENERATE_SALE_REPORT,
	//PERMISO PARA LA GESTION DE ANUNCIOS
	ADVERTISING_CREATE,
	//PERMISO PARA LA GESTION DE RECARGA DE T.A.
	RECHARGE_CREATE
	;
	
}